# FROM ubuntu:20.04
# RUN apt-get update
# ENV DEBIAN_FRONTEND=noninteractive
# RUN apt-get install apache2 -y
# COPY index.html /var/www/html/index.html
# expose 80
# CMD [ "apache2ctl", "-D", "FOREGROUND" ]
# # run code
# # docker build -t myapache2:v2 .
# # docker run -d -p 80:80 myapache2:v2
# # ps # inspect # curl


# # java tomcat apache
# FROM ubuntu:22.04     
# # version changr
# ENV TOMCAT_VERSION=9.0.115
# ENV DEBIAN_FRONTEND=noninteractive
# ENV TOMCAT_HOME=/opt/tomcat
# # add invironment only for ubuntu
# RUN apt-get update && \
#     apt-get install -y openjdk-21-jdk curl tar && \
#     rm -rf /var/lib/apt/lists/*
# # install java
# RUN curl -fSL https://dlcdn.apache.org/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz \
#     | tar -xz -C /opt && \
#     mv /opt/apache-tomcat-${TOMCAT_VERSION} ${TOMCAT_HOME}
# # tomcat install
# WORKDIR ${TOMCAT_HOME}/bin
# EXPOSE 8080
# # start tomcat
# CMD [ "./catalina.sh", "run" ]
# # run  # docker build -t tomcat:v3 .  ## -t is tag



# #chat gpt
# # Java + Tomcat + Apache
# FROM ubuntu:22.04

# ENV DEBIAN_FRONTEND=noninteractive
# ENV TOMCAT_VERSION=9.0.115
# ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
# ENV PATH=$JAVA_HOME/bin:$PATH

# # Install Java & curl
# RUN apt-get update && \
#     apt-get install -y openjdk-21-jdk curl && \
#     apt-get clean

# # Create opt directory
# RUN mkdir -p /opt

# # Download & extract Tomcat
# RUN curl -fSL https://dlcdn.apache.org/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz \
#     | tar -xzf - -C /opt

# # Set working directory
# WORKDIR /opt/apache-tomcat-${TOMCAT_VERSION}/bin

# # Expose Tomcat port
# EXPOSE 8080

# # Start Tomcat
# CMD ["./catalina.sh", "run"]


#############################
# Stage 1: Download Tomcat
FROM alpine:latest AS downloader

ENV TOMCAT_VERSION=9.0.115
WORKDIR /tmp

RUN apk add --no-cache curl tar && \
    curl -fSL https://dlcdn.apache.org/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz \
    -o tomcat.tar.gz && \
    tar -xzf tomcat.tar.gz

#############################
# Stage 2: Runtime Image
FROM mosipid/openjdk-21-jre:latest

ENV CATALINA_HOME=/opt/tomcat
ENV PATH=$CATALINA_HOME/bin:$PATH

VOLUME ["/data"]

COPY --from=downloader /tmp/apache-tomcat-* $CATALINA_HOME

EXPOSE 8080

CMD ["catalina.sh", "run"]






















