# FROM ubuntu:20.04
# RUN apt-get update
# ENV DEBIAN_FRONTEND=noninteractive
# RUN apt-get install apache2 -y
# COPY index.html /var/www/html/index.html
# expose 80
# CMD [ "apache2ctl", "-D", "FOREGROUND" ]
# # run code
# # docker build -t myapache2:v2
# # docker run -d -p 80:80 myapache2:v2
# # ps # inspect # curl


# java tomcat apache
FROM ubuntu:22.04     
# version changr
ENV DEBIAN_FRONTEND=noninteractive
# add invironment only for ubuntu
RUN apt-get update && \
    apt-get install openjdk-21-jdk -y curl
# install java
ENV TOMCAT_VERSION=9.0.115
RUN curl https://dlcdn.apache.org/tomcat/tomcat-9/v{TOMCAT_VERSION}/bin/apache-tomcat-{TOMCAT_VERSION}.tar.gz \
| tar -xzf -C /opt
# tomcat install
WORKDIR /opt/apache-tomcat-{TOMCAT_VERSION}/bin
EXPOSE 8080
# start tomcat
CMD [ "./catalina.sh", "run" ]
# run  # docker build -t tomcat:v3  ## -t is tag





























